### ISSUE TITLE
Button still visible even when the text is shorter than the specified min-height

### ISSUE THREAD

**Issue by roenfeldt** [DSekon/dReadmore#1]
@DSekon I love the plugin, but as the title says, this problem is a deal breaker to me, since I need the "Read more" functionality to be available for paragraphs where the text amount is highly variable.

More specifically, I intend to use it for user comments. Here's what I'm getting:
![Screen Shot 2020-06-12 at 21 33 23](https://user-images.githubusercontent.com/60813178/84541267-5d462880-acf7-11ea-8b1e-5c76ca788765.png)
![Screen Shot 2020-06-12 at 21 33 46](https://user-images.githubusercontent.com/60813178/84541270-5ddebf00-acf7-11ea-8112-5ec93bfbc380.png)

My settings:
```
// JS
$(".d-readmore").dReadmore({
    startOpen: false,
});
```

```
// CSS
.d-readmore {
    min-height: 3px;
    overflow: hidden;
}
```

Frankly I was thinking of programatically checking the character lenght of comment, and excluding the button in PHP, unless the comment is longer than xyz chars, but I feel like this would almost defeat the plugin's purpose. Is there any workaround to this issue?

On a side, totally unrelated note, is there any way of adding the "ellipsis" character (...) at the end of the initially-visible paragraph, i.e. before the text block is expanded?

Thanks a lot!

**Comment by DSekon** [comment]
@roenfeldt OMG, my bad. I just saw your comment recently . I didn't think anyone would need the plugin. Now I will develop it normally.
Regarding your questions, I fixed everything in v2.0.0.
About the ellipsis, I don't know yet, but in the future I think to implement a plugin for this.
