### ISSUE TITLE
Doesn't calculate default margin of heading tags

### ISSUE THREAD

**Issue by HelloTalib** [DSekon/dReadmore#3]
Hi there!,
Thanks for this awesome plugin. I have found a issue on your plugin. when I wrapped content by any kind of html tags your plugin doesn't calculate default margin. that's why this plugin doesn't match with proper height of the content . Is there any solution?
Issue: https://prnt.sc/26lu2ya
Regards.
Abu Talib

**Comment by DSekon** [comment]
> Hi there!, Thanks for this awesome plugin. I have found a issue on your plugin. when I wrapped content by any kind of html tags your plugin doesn't calculate default margin. that's why this plugin doesn't match with proper height of the content . Is there any solution? Issue: https://prnt.sc/26lu2ya Regards. Abu Talib

Hi, Thank you. I'm very pleased that you liked the plugin. 
![image](https://user-images.githubusercontent.com/26517397/151694171-eec4fc90-c214-4e2c-85fc-2186b3822447.png)
The plugin was made more for text and inline tags inside. For what purpose do you need indented inside?

**Comment by DSekon** [comment]
Although it is possible for two p tags in a row to be indented. There will of course be a problem with line counting.
But a top indent of a first element, it would be better to put it on the container (in my case, div.item) than on the inner element.

**Comment by HelloTalib** [comment]
Hi!, I have some dynamic content that's wrapped with all of html tags. that's why, I need to wrapped this content text with tags. It's not possible to add "dreadmore" class in my content text.
https://prnt.sc/26lvlnn

**Comment by DSekon** [comment]
> Hi!, I have some dynamic content that's wrapped with all of html tags. that's why, I need to wrapped this content text with tags. It's not possible to add "dreadmore" class in my content text. https://prnt.sc/26lvlnn

Okay, I hear you. When I release the update, I'll let you know. Probably today or tomorrow.

**Comment by HelloTalib** [comment]
Sounds good,
another feature request. It will be awesome, If you try to  build this plugin to reduce html tags as much as possible😊

**Comment by DSekon** [comment]
> Sounds good, another feature request. It will be awesome, If you try to build this plugin to use less html tags as much as possible😊

Added version 2.1.0 to github for now. Tomorrow I will add the plugin to npm.
The condition that will use the tag count: only tags must be inside a .drreadmore.
I also reduced the number of tags used.

**Comment by abutalib4599** [comment]
**Fantastic job!** you're doing so far, but still have some issues with **H1** and **P** tags.

**Comment by HelloTalib** [comment]
**Fantastic job!** you're doing so far, Thanks for quick response, keep up with the good work!
